version: '3.8'
services:
    java-app:
      container_name: java-backend-compose
      image: "openjdk:17-jdk-slim"
      restart: always
      working_dir: /app
      volumes:
        - "/Users/vadim/Downloads/Java/Java practice/car_rental_project/backend/target/car-rental-rest-service-0.0.1-SNAPSHOT.jar:/app/app.jar"
      environment:
        - "ENVIRONMENT=production"
        - "PORT=9090"
      ports:
        - "9090:9090"
      command: ["java", "-Dspring.profiles.active=test", "-jar", "app.jar"]
    postgres:
      container_name: postgres-backend-compose
      image: "postgres:${POSTGRES_VERSION}"
      restart: always
    #    volumes:
    #      - "./postgres/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh"
    #      - "./postgres/init-database.sql:/docker-entrypoint-initdb.d/init-database.sql"
      tmpfs:
        - "/var/lib/postgresql/data:rw"
      environment:
        - "POSTGRES_USER=${POSTGRES_USER}"
        - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
        - "POSTGRES_DB=${POSTGRES_DB}"
      ports:
        - "${POSTGRES_PORT}:5432"