ALTER TABLE cars
    ADD COLUMN number VARCHAR(36) NOT NULL,
    ADD COLUMN color VARCHAR(36) NOT NULL,
    ADD COLUMN VIN VARCHAR(36) NOT NULL,
    ADD COLUMN year INTEGER NOT NULL,
    ADD COLUMN body_type VARCHAR(36) NOT NULL,
    ADD COLUMN fuel_tank_capacity INTEGER NOT NULL,
    ADD COLUMN trunk_capacity INTEGER NOT NULL;
