ALTER TABLE cars
    ALTER COLUMN car_class TYPE VARCHAR(50);

ALTER TABLE cars
    ALTER COLUMN fuel_type TYPE VARCHAR(50);

ALTER TABLE cars
    ALTER COLUMN gearbox_type TYPE VARCHAR(50);

ALTER TABLE cars
    ALTER COLUMN drive_type TYPE VARCHAR(50);