spring.application.name = car-rental-rest-service
server.port=9090

logging.level.org.springframework.security=DEBUG

#db
spring.datasource.url = jdbc:postgresql://localhost:15433/backend
spring.datasource.password = 12345678
spring.datasource.username = postgres
spring.datasource.driver-class-name = org.postgresql.Driver
spring.jpa.hibernate.ddl-auto = validate
#spring.jpa.properties.hibernate.show_sql = true
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql = true

spring.reactor.debug-agent.enabled=true
spring.datasource.hikari.pool-name=RestDB-Pool
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.data-source-properties.cachePrepStmts=true
spring.datasource.hikari.data-source-properties.prepStmtCacheSize=250
spring.datasource.hikari.data-source-properties.prepStmtCacheSqlLimit=2048
spring.datasource.hikari.data-source-properties.useServerPrepStmts=true
spring.datasource.hikari.data-source-properties.useLocalSessionState=true
spring.datasource.hikari.data-source-properties.rewriteBatchedStatements=true
spring.datasource.hikari.data-source-properties.cacheResultSetMetadata=true
spring.datasource.hikari.data-source-properties.cacheServerConfiguration=true
spring.datasource.hikari.data-source-properties.elideSetAutoCommits=true
spring.datasource.hikari.data-source-properties.maintainTimeStats=false

logging.level.org.hibernate.orm.jdbc.bind = trace

#flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1.0
spring.flyway.baseline-description=init



#mailing service
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vadym.peniaka.kn.2021@lpnu.ua
spring.mail.password=herb whpq lcom slmj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8

#s3
do.space.key=DO00XCU9AAFTZX3V3EVA
do.space.secret=HJ+f4uypyypzn072hPkMszcOOoZU6D1EmgMbntjwxow
do.space.endpoint=https://carrental.fra1.digitaloceanspaces.com
do.space.region=fra1
do.space.bucket=cars
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
#endpoint+bucket+folderName+filename+extension

#bank id
bank.id.secret_key=V3ry_S3cr3t_K3y_1O10
bank.id.url=http://localhost:8080/api/v1/info/get

#ai

#payment
stripe.api.key=sk_test_51REycIQ0fxz698wxMJI1Wl5awEQrDaH68rtcIOmmOQ5fUURFydW1fkV9g4gSYkuBZNKe0d0w2hSlZbGqLoNeS1b100iLyQGZMN
